# Generated by Django 4.1.7 on 2023-02-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    def insert_init_data(apps, schema_editor):
        
        tipoPlaza = apps.get_model('ParkingLotApp', 'TipoPlaza')
        tipoPlaza.objects.create(descripcion='Grande', ancho=3.00, largo=5.00, discap=False)
        tipoPlaza.objects.create(descripcion='Pequeña', ancho=2.20, largo=5.00, discap=False)
        tipoPlaza.objects.create(descripcion='Discapacitados', ancho=3.00, largo=5.00, discap=True)
           
    def undo_insert_data(apps,schema_editor):
        tipoPlaza = apps.get_model('ParkingLotApp', 'TipoPlaza')
        tipoPlaza.objects.all().delete()
    
    operations = [
        migrations.CreateModel(
            name='TipoPlaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('ancho', models.FloatField()),
                ('largo', models.FloatField()),
                ('discap', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'tipoPlaza',
                'verbose_name_plural': 'tiposPlaza',
            },
        ),
        migrations.RunPython(insert_init_data, reverse_code=undo_insert_data)
    ]
