# Generated by Django 4.1.7 on 2023-02-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0002_alter_parking_num_plazas_discap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='num_plazas_discap',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='num_plazas_grandes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='num_plazas_peq',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
