# Generated by Django 4.1.7 on 2023-02-27 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0003_alter_parking_num_plazas_discap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='cubierto',
        ),
    ]
