# Generated by Django 4.1.7 on 2023-02-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0006_parking_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='num_plazas_discap',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='num_plazas_grandes',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='num_plazas_peq',
        ),
    ]
