# Generated by Django 4.1.7 on 2023-02-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0007_remove_parking_num_plazas_discap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='observaciones',
            field=models.TextField(default='', max_length=300, null=True),
        ),
    ]
