# Generated by Django 4.1.7 on 2023-02-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0008_alter_parking_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='cubierto',
            field=models.BooleanField(default=False),
        ),
    ]
