# Generated by Django 4.1.7 on 2023-02-27 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edificios', '0002_rename_id_edificio_edificio_id_parking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('max_plazas', models.IntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('id_edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificios.edificio')),
            ],
            options={
                'verbose_name': 'planta',
                'verbose_name_plural': 'plantas',
            },
        ),
    ]
