# Generated by Django 4.1.7 on 2023-02-27 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zonas', '0003_zona_observaciones'),
        ('ParkingLotApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('id_tipo_plaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParkingLotApp.tipoplaza')),
                ('id_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zonas.zona')),
            ],
            options={
                'verbose_name': 'plaza',
                'verbose_name_plural': 'plazas',
            },
        ),
    ]
