# Generated by Django 4.1.7 on 2023-03-21 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0003_zona_observaciones'),
        ('plazas', '0002_remove_plaza_id_zona_plaza_id_planta'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaza',
            name='id_zona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zonas.zona'),
            preserve_default=False,
        ),
    ]
