# Generated by Django 4.1.7 on 2023-03-21 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plazas', '0003_plaza_id_zona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plaza',
            name='id_planta',
        ),
    ]
