# Generated by Django 4.1.7 on 2023-03-21 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0001_initial'),
        ('plazas', '0004_remove_plaza_id_planta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plaza',
            name='id_zona',
        ),
        migrations.AddField(
            model_name='plaza',
            name='id_planta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plantas.planta'),
            preserve_default=False,
        ),
    ]
