# Generated by Django 4.1.7 on 2023-02-27 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parkings', '0010_alter_parking_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('id_edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkings.parking')),
            ],
            options={
                'verbose_name': 'edificio',
                'verbose_name_plural': 'edificios',
            },
        ),
    ]
