# Generated by Django 4.1.7 on 2023-02-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edificio',
            old_name='id_edificio',
            new_name='id_parking',
        ),
    ]
